# Generated by Django 2.2.2 on 2019-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=300)),
                ('categorie', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=1)),
                ('picture', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
