# Generated by Django 2.2.2 on 2019-06-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_favorite_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsNutriTypeA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('product_name', models.CharField(default='00', max_length=300)),
                ('picture', models.CharField(default='00', max_length=500)),
                ('category', models.CharField(default='00', max_length=200)),
            ],
        ),
    ]
