# Generated by Django 2.2.2 on 2019-06-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productsnutritypea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsnutritypea',
            name='code',
        ),
    ]
